/**
 * raccoon_bot
 * raccoon_bot
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BotGroupTopicEntity { 
    createTime?: number;
    groupId?: number;
    id?: number;
    msgEndId?: number;
    msgIgnoreIdsJson?: string;
    msgStartId?: number;
    senderId?: number;
    status?: string;
    title?: string;
    topicKey?: string;
    type?: number;
}
