/**
 * raccoon_bot
 * raccoon_bot
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface BotMessageEntity { 
    content?: string;
    createTime?: number;
    groupId?: number;
    id?: number;
    isDel?: boolean;
    isTrainable?: boolean;
    labelCrtype?: string;
    labelFirst?: string;
    labelSecond?: string;
    labelType?: number;
    lfPby?: number;
    lsPby?: number;
    msgId?: number;
    senderId?: number;
    senderNick?: string;
}
