/**
 * raccoon_bot
 * raccoon_bot
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BotGroupTopicEntity } from './botGroupTopicEntity';
import { BotMessageEntity } from './botMessageEntity';


export interface TopicInfoResponse { 
    msgList?: Array<BotMessageEntity>;
    topic?: BotGroupTopicEntity;
}
